// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngpxsyolpqlinnziksag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ncHhzeW9scHFsaW5uemlrc2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDMyMjksImV4cCI6MjA3MjU3OTIyOX0.yftdZEoEfqNVZz2IoAi0TiEo0vowtN1zIcn-Iz4La4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});